name: nexovault
description: Gestor de contraseñas local y seguro para Android.
publish_to: 'none'
version: 0.1.4+5

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.3.1
  local_auth: ^3.0.2
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/nexovault_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/nexovault_icon.png"
  adaptive_icon_background: "#0B1020"
  adaptive_icon_foreground: "assets/icons/nexovault_icon.png"
  min_sdk_android: 24

# Fijado temporalmente para evitar una incompatibilidad de Gradle en jni 1.0.1.
dependency_overrides:
  jni: 1.0.0
